name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tf-keras
        pip install pytest

    - name: Check for open ports
      run: netstat -a

    - name: Run application
      run: |
       python main.py > app.log 2>&1 &
       

    # Step 5: Wait for the application to start (optional)
    - name: Wait for the app to start
      shell: bash
      run: |
        curl http://localhost:80
        echo "Application started successfully!"
        timeout=60
        echo "Waiting for the application to start at http://localhost:8080..."
        while ! curl -s http://localhost:80; do
          ((timeout--))
          if [ $timeout -le 0 ]; then
            echo "Application failed to start within the timeout period."
            exit 1
          fi
            echo "Application not ready yet. Retrying in 1 second..."
            sleep 1
        done
