name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tf-keras

    - name: Run application
      run: |
       python app.py
      env:
        PORT: 8080  # Example of setting environment variables if needed

    # Step 5: Wait for the application to start (optional)
    - name: Wait for the app to start
      run: |
        timeout=30
        while ! curl -s http://localhost:8080; do
          ((timeout--))
          if [ $timeout -le 0 ]; then
            echo "Application failed to start."
            exit 1
          fi
          sleep 1
        done

    # Step 6: Run pytest
    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings -v
