name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        py -m pip install --upgrade pip
        py -m pip install pytest
        py -m pip install -r requirements.txt
    - name: Deploy python app
      run: python app.py
    - name: Test with pytest
      run: pytest
